name: CI
on:
  pull_request:
    branches: [ main ]
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: oracle

      - name: Check
        uses: gradle/gradle-build-action@v3
        with:
          arguments: check

      - name: Assemble
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assemble
